# -------------------------
# Base URL
# -------------------------
@baseUrl = http://localhost:5046/api

# -------------------------
# Show Genres
# -------------------------

### Get all genres assigned to a show
GET {{baseUrl}}/shows/1/genres
Accept: application/json

### Add a genre to a show
POST {{baseUrl}}/shows/1/genres/3
Accept: application/json

### Replace all genres for a show
PUT {{baseUrl}}/shows/1/genres
Content-Type: application/json

[ 1, 2, 3 ]

### Remove a genre from a show
DELETE {{baseUrl}}/shows/1/genres/3
Accept: application/json


