@baseUrl = http://localhost:5046/api

### Get all shows
GET {{baseUrl}}/shows
Accept: application/json

### Get a single show by ID
GET {{baseUrl}}/shows/1
Accept: application/json

### Create a new show
POST {{baseUrl}}/shows
Content-Type: application/json

{
  "title": "The Witcher",
  "description": "A monster hunter navigates a dark fantasy world.",
  "releaseDate": "2019-12-20"
}

### Update an existing show (PUT)
PUT {{baseUrl}}/shows/1
Content-Type: application/json

{
  "title": "Stranger Things Updated",
  "description": "Updated description for Stranger Things.",
  "releaseDate": "2016-07-15"
}

### Delete a show by ID
DELETE {{baseUrl}}/shows/4
Accept: application/json
