### Get all shows
GET http://localhost:5046/shows
Accept: application/json

### Get a single show by ID
GET http://localhost:5046/shows/1
Accept: application/json

### Create a new show
POST http://localhost:5046/shows
Content-Type: application/json

{
  "title": "The Witcher",
  "description": "A monster hunter navigates a dark fantasy world.",
  "releaseDate": "2019-12-20"
}

### Update an existing show (PUT)
PUT http://localhost:5046/shows/1
Content-Type: application/json

{
  "title": "Stranger Things Updated Twice",
  "description": "Updated description for Stranger Things.",
  "releaseDate": "2016-07-15",
  "genres": [1, 2, 3, 4]
}

### Delete a show by ID
DELETE http://localhost:5046/shows/4
Accept: application/json
